#ifndef _VERSION_NUMBER_INFO_H
#define _VERSION_NUMBER_INFO_H

#define VERSION_NAME_LENGTH 16 
#define VERSION_NUMBER_LENGTH 7
#define VERSION_NAME "OHD-CORE-CHPS-"
#define VERSION_NUMBER "TRUNK"
#endif
